### ISSUE TITLE
Release 1.1 - AWX - UndefinedVariable

### ISSUE THREAD

**Issue by piotron** [kravietz/ansible-ipsec#3]
Hi, after your recent changes we started to have issues with this playbook.
step `ipse-tools configuration`  returns
```
{
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'address'",
    "_ansible_notify": [
        "setkey restart"
    ],
    "changed": false,
    "_ansible_no_log": false
}
```

Everything works to 2a344d98af2e24a75871c6f917af61238b49605c after that we're getting message above.
Our servers are running on Ubuntu, some may not have ipv6 interfaces.

**Comment by kravietz** [comment]
@piotron IPv6 parts should be only enabled if there's a routable IPv6 address on the host , as determined by `ansible_default_ipv6` structure, and only then  `ansible_default_ipv6.address` is accessed. Do you have fact caching enabled? Are you using `ipsec_forward: yes`?

**Comment by piotron** [comment]
@kravietz I'm not using fact caching, I'm using setup on beginning of each playbook.
```
- hosts: all
  pre_tasks:
    - setup:
  tasks:
    - import_role:
        name: kravietz.ipsec
      vars:
        ipsec_secret: "{{ IPSEC_SECRET | mandatory }}"
        ipsec_policy: use
        ipsec_open_icmp: yes
        ipsec_open_ssh: yes
        ipsec_forward: yes
      become: true
      become_user: root
```
