### ISSUE TITLE
Possible bug - ipsec_inet setting is not being respected

### ISSUE THREAD

**Issue by saurabhnanda** [kravietz/ansible-ipsec#9]
I have the following config:

```
- hosts: all
  roles:
    - name: ansible-ipsec
      vars:
        ipsec_secret: "REDACTED"
        ipsec_inet:
          - ansible_default_ipv4
        ipsec_policy: require
        ipsec_mode: ike
        ipsec_open_ssh: true
        ipsec_open_icmp: true
        ipsec_forward: false
        ipsec_compress: true
```

But, I can see the following snippets in `/etc/ipsec-tools.conf`:

```
### SPD entries for storefront/2a01:4f9:c010:8d7::1 <-> dataserver/2a01:4f9:2b:3cc::2

# storefront -> dataserver
spdadd 2a01:4f9:c010:8d7::1 2a01:4f9:2b:3cc::2 any -P out ipsec ipcomp/transport//use esp/transport//require;
# dataserver -> storefront
spdadd 2a01:4f9:2b:3cc::2 2a01:4f9:c010:8d7::1 any -P in  ipsec ipcomp/transport//use esp/transport//require;
```
